obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_bin_parse.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_calib.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_device.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_dsp.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_init.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_monitor.o
obj-$(CONFIG_SND_SOC_AW882xx) += aw882xx_spin.o
